# gpu-worker/.github/workflows/docker-build.yml

name: Build and Push GPU Worker Image

# This tells GitHub to run this workflow every time you push to the 'main' branch
on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Run this on a standard Linux server

    steps:
      # Step 1: Check out your repository code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Log in to Docker Hub using the secrets we created
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: This is the main step that builds and pushes the image
      # It uses your DOCKERHUB_USERNAME secret to correctly tag the image.
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: . 
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/alvis-gpu-worker:latest